### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by commandz0** [adriweb/tivars_lib_cpp#12]
It would be useful to have a command-line version of this library for use in makefiles and shell scripts.
I've made one for personal use but I'm dissatisfied with its interface.

I think that a format similar to convbin would work well - something like `tivars --iformat=(raw|readable|varfile) --oformat=(raw|readable|varfile) --input=(file) --output=(file)`.

Some other options that would be useful:
- `--type` Variable type (e.g. Program, RealList)
- `--name` The program or variable name, if iformat or oformat is varfile
- `--calc` The calculator type this variable is for
- `--csv` A CSV file of tokens to be appended to the internal one.
- `--lang` The language code to use
- `--reindent`, `--prettify`, `--detect_strings` Boolean flags for tokenized variables

**Comment by adriweb** [comment]
Let's work on that in the feature/cli branch.
