### ISSUE TITLE
How do you convert a python file to .8xv?

### ISSUE THREAD

**Issue by ghost** [adriweb/tivars_lib_cpp#22]
The examples in tests.cpp (from what i read) only show doing it the other way around, or .8xv to python. In my case, I want to convert a python file into .8xv to load onto my ti84 plus ce, so how would I do it?

Thanks in advance

**Comment by adriweb** [comment]
There is actually a test that shows this: https://github.com/adriweb/tivars_lib_cpp/blob/f57a964ef41e8cd7dd4bd5af6e471205008f64ef/tests.cpp#L438-L440 :)
