### ISSUE TITLE
Tokens sometimes not tokenized properly

### ISSUE THREAD

**Issue by commandz0** [adriweb/tivars_lib_cpp#8]
Some multi-byte tokens are sometimes not tokenized properly when setting a program's contents. Instead, they are tokenized as the corresponding uppercase and lowercase letters.
I have no idea what's causing this, and I'm also having trouble finding a minimal case, as changing anything in the program causes it to randomly stop or start working again.
Here's the project I'm currently working on. SetUpEditor is not being tokenized properly:
```
SetUpEditor ⌊BZARG
If dim(⌊BZARG):Then
  ⌊BZARG→L₂
  DelVar ⌊BZARG
If L₂(1)=0:Then
  ClrHome
  Output(1, 1, "Error:")
  Output(1, 8, Str1)
  Output(9, 1, Str2)
  Output(10, 1, "Line")
  Output(10, 6, L₂(2))
  While not(getKey):End
  Stop
End
  Return
End
"Auto-generated."
"Original code:"
"https://git.io/     "
"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789θ"→Str1
DelVar X
DelVar Y
DelVar M
DelVar P
DelVar S
DelVar L
DelVar C
DelVar I
DelVar E
While getKey≠45
  L₂(P)
  Disp Ans
  P+1→P
End
Lbl 0
```

**Comment by adriweb** [comment]
Fixed in 570b9273ddeb49180150b0902e999ffb60e4bf1a
